### ISSUE TITLE
Error after add a package/dataset - CKAN 2.6.2

### ISSUE THREAD

**Issue by thenets** [ckan/ckanext-archiver#49]
I got this error when I try to add a new package:

```
2017-06-21 10:36:32,052 INFO  [ckan.lib.base]  /api/i18n/en render time 0.008 seconds
/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py:79: SAWarning: Usage of the 'related attribute set' operation is not currently supported within the execution stage of the flush process. Results may not be consistent.  Consider using alternative event listeners or connection-level operations instead.
  sess._flush_warning("related attribute set")
2017-06-21 10:36:39,449 ERROR [ckan.model.modification] (ProgrammingError) relation "archival" does not exist
LINE 2: FROM archival JOIN resource ON archival.resource_id = resour...
             ^
 'SELECT archival.id AS archival_id, archival.package_id AS archival_package_id, archival.resource_id AS archival_resource_id, archival.resource_timestamp AS archival_resource_timestamp, archival.status_id AS archival_status_id, archival.is_broken AS archival_is_broken, archival.reason AS archival_reason, archival.url_redirected_to AS archival_url_redirected_to, archival.cache_filepath AS archival_cache_filepath, archival.cache_url AS archival_cache_url, archival.size AS archival_size, archival.mimetype AS archival_mimetype, archival.hash AS archival_hash, archival.etag AS archival_etag, archival.last_modified AS archival_last_modified, archival.first_failure AS archival_first_failure, archival.last_success AS archival_last_success, archival.failure_count AS archival_failure_count, archival.created AS archival_created, archival.updated AS archival_updated \nFROM archival JOIN resource ON archival.resource_id = resource.id \nWHERE archival.package_id = %(package_id_1)s AND resource.state = %(state_1)s' {'package_id_1': u'cc687cd5-3f7e-4011-8142-80d20965227f', 'state_1': 'active'}
Traceback (most recent call last):
  File "/usr/lib/ckan/default/src/ckan/ckan/model/modification.py", line 88, in notify
    observer.notify(entity, operation)
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/search/__init__.py", line 130, in notify
    {'id': entity.id}),
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/__init__.py", line 431, in wrapped
    result = _action(context, data_dict, **kw)
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/action/get.py", line 1011, in package_show
    item.after_show(context, package_dict)
  File "/usr/lib/ckan/default/src/ckanext-archiver/ckanext/archiver/plugin.py", line 184, in after_show
    archivals = Archival.get_for_package(pkg_dict['id'])
  File "/usr/lib/ckan/default/src/ckanext-archiver/ckanext/archiver/model.py", line 143, in get_for_package
    .filter(model.Resource.state=='active') \
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2293, in all
    return list(self)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2405, in __iter__
    return self._execute_and_instances(context)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2420, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 727, in execute
    return meth(self, multiparams, params)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 322, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 824, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 954, in _execute_context
    context)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1116, in _handle_dbapi_exception
    exc_info
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 189, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 947, in _execute_context
    context)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 435, in do_execute
    cursor.execute(statement, parameters)
ProgrammingError: (ProgrammingError) relation "archival" does not exist
LINE 2: FROM archival JOIN resource ON archival.resource_id = resour...
             ^
 'SELECT archival.id AS archival_id, archival.package_id AS archival_package_id, archival.resource_id AS archival_resource_id, archival.resource_timestamp AS archival_resource_timestamp, archival.status_id AS archival_status_id, archival.is_broken AS archival_is_broken, archival.reason AS archival_reason, archival.url_redirected_to AS archival_url_redirected_to, archival.cache_filepath AS archival_cache_filepath, archival.cache_url AS archival_cache_url, archival.size AS archival_size, archival.mimetype AS archival_mimetype, archival.hash AS archival_hash, archival.etag AS archival_etag, archival.last_modified AS archival_last_modified, archival.first_failure AS archival_first_failure, archival.last_success AS archival_last_success, archival.failure_count AS archival_failure_count, archival.created AS archival_created, archival.updated AS archival_updated \nFROM archival JOIN resource ON archival.resource_id = resource.id \nWHERE archival.package_id = %(package_id_1)s AND resource.state = %(state_1)s' {'package_id_1': u'cc687cd5-3f7e-4011-8142-80d20965227f', 'state_1': 'active'}
2017-06-21 10:36:39,464 DEBUG [ckanext.archiver.plugin] Notified of package event: 123123123 new
2017-06-21 10:36:39,472 DEBUG [ckanext.archiver.plugin] New package - will archive
2017-06-21 10:36:39,473 DEBUG [ckanext.archiver.plugin] Creating archiver task: 123123123
2017-06-21 10:36:39,604 DEBUG [ckanext.archiver.lib] Archival of package put into celery queue priority: 123123123
Debug at: http://localhost:5000/_debug/view/1498041399
```

It looks like some incompatible with 2.6.x version after some migration.

**Comment by thenets** [comment]
Sorry.
Was my mistake. I reseted my database and forgot to run archiver migration again.
