### ISSUE TITLE
ERROR [ckanext.archiver.tasks] Error occurred during archiving package: 'NoneType' object has no attribute 'ugettext'

### ISSUE THREAD

**Issue by psonis** [ckan/ckanext-archiver#59]
When I use the extension in the terminal I get an error...

The backup/archive completes just fine, and CKAN adds all the info in the resource page (Link is ok, Link checked, Download cached copy, Size,Cached on)

After completing the archiving I get this and the process does to exit..

`2018-07-19 11:59:34,908 INFO  [ckanext.archiver.tasks] Notifying package as 1 items were archived
2018-07-19 11:59:34,941 ERROR [ckanext.archiver.tasks] Error occurred during archiving package: 'NoneType' object has no attribute 'ugettext'
Package: 857b7063-f48a-46dc-9777-ed2f55742de5
[2018-07-19 11:59:34,950: ERROR/MainProcess] Task archiver.update_package[another-test/1738] raised unexpected: AttributeError("'NoneType' object has no attribute 'ugettext'",)
Traceback (most recent call last):
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/hit/ckan/lib/default/src/ckanext-archiver/ckanext/archiver/tasks.py", line 150, in update_package
    _update_package(ckan_ini_filepath, package_id, queue, log)
  File "/home/hit/ckan/lib/default/src/ckanext-archiver/ckanext/archiver/tasks.py", line 186, in _update_package
    _update_search_index(package_id, log)
  File "/home/hit/ckan/lib/default/src/ckanext-archiver/ckanext/archiver/tasks.py", line 200, in _update_search_index
    package = toolkit.get_action('package_show')(context_, {'id': package_id})
  File "/home/hit/ckan/lib/default/src/ckan/ckan/logic/__init__.py", line 431, in wrapped
    result = _action(context, data_dict, **kw)
  File "/home/hit/ckan/lib/default/src/ckan/ckan/logic/action/get.py", line 976, in package_show
    package_dict = model_dictize.package_dictize(pkg, context)
  File "/home/hit/ckan/lib/default/src/ckan/ckan/lib/dictization/model_dictize.py", line 301, in package_dictize
    result_dict['license_title'] = pkg.license.title.split('::')[-1]
  File "/home/hit/ckan/lib/default/src/ckan/ckan/model/license.py", line 50, in __getattr__
    return self._data[name]
  File "/home/hit/ckan/lib/default/src/ckan/ckan/model/license.py", line 201, in __getitem__
    value = getattr(self, key)
  File "/home/hit/ckan/lib/default/src/ckan/ckan/model/license.py", line 272, in title
    return _("Creative Commons Attribution")
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pylons/i18n/translation.py", line 106, in ugettext
    return pylons.translator.ugettext(value)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/registry.py", line 137, in __getattr__
    return getattr(self._current_obj(), attr)
AttributeError: 'NoneType' object has no attribute 'ugettext'
`

**Comment by psonis** [comment]
installing the QA extensions and running it again, gives a different error.

The archiver process seems to work now but QA give this error

`[2018-07-19 14:09:00,834: INFO/MainProcess] Task archiver.update_package[test/4098] succeeded in 4.3282878s: None
[2018-07-19 14:09:00,839: ERROR/MainProcess] Task qa.update_package[another-test-1aad] raised unexpected: AttributeError("'update_package' object has no attribute 'get_logger'",)
Traceback (most recent call last):
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/hit/ckan/lib/default/src/ckanext-qa/ckanext/qa/tasks.py", line 83, in update_package
    log = update_package.get_logger()
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/celery/local.py", line 143, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'update_package' object has no attribute 'get_logger'
[2018-07-19 14:09:00,844: ERROR/MainProcess] Task qa.update_package[test-d55a] raised unexpected: AttributeError("'update_package' object has no attribute 'get_logger'",)
Traceback (most recent call last):
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/hit/ckan/lib/default/src/ckanext-qa/ckanext/qa/tasks.py", line 83, in update_package
    log = update_package.get_logger()
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/celery/local.py", line 143, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'update_package' object has no attribute 'get_logger'
`

**Comment by Zharktas** [comment]
Fixed in #55.
